services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: application_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: ${DOCKER_USERNAME}/application-tracker:migrator
    restart: no
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/application_tracker"
    depends_on:
      db:
        condition: service_healthy
    command:
      ["sh", "-c", "node node_modules/prisma/build/index.js migrate deploy"]

  app:
    image: ${DOCKER_USERNAME}/application-tracker:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/application_tracker"
      HOSTNAME: "0.0.0.0"
    depends_on:
      migrate:
        condition: service_completed_successfully

volumes:
  postgres_data:
